ezpublish:
    system:
        admin_group:
            fieldtypes:
                ezrichtext:
                    custom_tags: [ezbutton, ezyoutube]
    ezrichtext:
        custom_tags:
            ezbutton:
                template: '@ezdesign/fields/ezrichtext/custom_tags/ezbutton.html.twig'
                icon: '/bundles/ezplatformadminui/img/ez-icons.svg#form'
                attributes:
                    url:
                        type: 'string'
                        required: true
                    title:
                        type: 'string'
                        required: true
                    target:
                        type: 'string'
                        required: false
                    class:
                        type: 'string'
                        required: false

            ezyoutube:
                template: '@ezdesign/fields/ezrichtext/custom_tags/ezyoutube.html.twig'
                icon: '/bundles/ezplatformadminui/img/ez-icons.svg#video'
                attributes:
                    video_url:
                        type: 'string'
                        required: true
                    width:
                        type: 'number'
                        required: true
                        default_value: 640
                    height:
                        type: 'number'
                        required: true
                        default_value: 360
                    autoplay:
                        type: 'boolean'
                        default_value: false
