services:
    app.pagerfanta.template.package_list:
        class: AppBundle\View\Template\PackageListTemplate

    pagerfanta.view.package_list:
        class: Pagerfanta\View\DefaultView
        public: false
        arguments:
            - "@app.pagerfanta.template.package_list"
        tags:
            - { name: pagerfanta.view, alias: package_list }
