services:
    app.twig_extension.field_options:
        class: AppBundle\Twig\FieldOptionsTwigExtension
        arguments:
            - '@ezpublish.api.service.content_type'
        tags:
            - name: twig.extension

    AppBundle\Twig\YoutubeIdExtractorExtension:
        tags:
            - { name: twig.extension }
